spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gis_alpha_test
    username: gis_alpha_test_app
    password: dev1
  jpa:
    open-in-view: false
    properties:
      hibernate.default_schema: gis_alpha_test
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: ${spring.jpa.properties.hibernate.default_schema}
  freemarker:
    settings:
      output_format: HTMLOutputFormat
      template_exception_handler: rethrow
    suffix: .ftl
branding:
  service:
    name: GIS Alpha Test
    mnemonic: GISAT
    support-contact:
      email: example@xyz.com
      phone: xyz123
  customer:
    name: North Sea Transition Authority
    mnemonic: NSTA

grpc:
  client:
    node-server:
      address: static://localhost:8082
      negotiation-type: plaintext