spring:
  datasource:
    url: jdbc:tc:postgresql:16:///test
    username: user
    password: password
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    oracle:
      url: jdbc:h2:mem:testdb
      username: ''
      password: ''
      driver-class-name: org.h2.Driver
      flyway:
        enabled: false
